name: Push

on: push

jobs:

  Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm install
      - name: ESlint
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Transpile
        run: npm run build
